###
POST http://localhost:8085/api/v1/products
Content-Type: application/json

{
    "name": "ismail",
    "description": "Ceci est un produit de test1",
    "unitPrice": 200,
    "quantity": 12
}
###

GET http://localhost:8085/api/v1/products

###

PUT http://localhost:8085/api/v1/products/add-quantity/352
Content-Type: application/json

{
    "quantityToAdd" : 5,
    "prixAchat" : 20.50
}
###
PATCH http://localhost:8085/api/v1/products/reduce-quantity/202
Content-Type: application/json

{
    "quantityToReduce" : 3
}