###
#POST http://localhost:8080/api/v1/commandes
#Content-Type: Application/json
#
#{
#  "nomProduit": "string12342",
#
#  "quantiteProduit": 30,
#
#  "status": "EN_ATTENTE",
#
#  "idFournisseur": 1,
#
#  "idProduit": 202
#}

###
POST http://localhost:8080/api/v1/commandes
Content-Type: application/json

{
  "idFournisseur": 1,
  "produits": [
    {
      "produitId": 303,
      "quantite": 7
    },
    {
      "produitId": 352,
      "quantite": 7
    }
  ]
}

###
# Récupérer toutes les commandes avec les détails des produits
GET http://localhost:8080/api/v1/commandes

###
# Récupérer une commande par ID avec les détails des produits
GET http://localhost:8080/api/v1/commandes/1

###
# Supprimer une commande
DELETE http://localhost:8080/api/v1/commandes/1

###
# Mettre à jour le statut d'une commande (changement vers LIVREE)
PATCH http://localhost:8080/api/v1/commandes/19/status
Content-Type: application/json

{
  "status": "LIVREE"
}

###
# Mettre à jour le statut d'une commande (changement vers EN_COURS)
PATCH http://localhost:8080/api/v1/commandes/2/status
Content-Type: application/json

{
  "status": "EN_COURS"
}
